//
//  NationalDays.swift
//  PodConnect
//

import Foundation

/// Keyed by "MM-dd"
let nationalDays: [String: String] = [
    "01-01": "National New Year's Day",
    "01-02": "National Science Fiction Day",
    "01-03": "National Chocolate Covered Cherry Day",
    "01-04": "National Spaghetti Day",
    "01-05": "National Bird Day",
    "01-06": "National Bean Day",
    "01-07": "National Tempura Day",
    "01-08": "National Bubble Bath Day",
    "01-09": "National Apricot Day",
    "01-10": "National Houseplant Appreciation Day",
    "01-11": "National Milk Day",
    "01-12": "National Marzipan Day",
    "01-13": "National Rubber Ducky Day",
    "01-14": "National Dress Up Your Pet Day",
    "01-15": "National Bagel Day",
    "01-16": "National Fig Newton Day",
    "01-17": "National Hot Buttered Rum Day",
    "01-18": "National Thesaurus Day",
    "01-19": "National Popcorn Day",
    "01-20": "National Cheese Lovers Day",
    "01-21": "National Hugging Day",
    "01-22": "National Blonde Brownie Day",
    "01-23": "National Pie Day",
    "01-24": "National Compliment Day",
    "01-25": "National Opposite Day",
    "01-26": "National Peanut Brittle Day",
    "01-27": "National Chocolate Cake Day",
    "01-28": "National Blueberry Pancake Day",
    "01-29": "National Puzzle Day",
    "01-30": "National Croissant Day",
    "01-31": "National Backwards Day",
    "02-01": "National Dark Chocolate Day",
    "02-02": "National Groundhog Day",
    "02-03": "National Carrot Cake Day",
    "02-04": "National Homemade Soup Day",
    "02-05": "National Weatherperson's Day",
    "02-06": "National Frozen Yogurt Day",
    "02-07": "National Send a Card to a Friend Day",
    "02-08": "National Kite Flying Day",
    "02-09": "National Pizza Day",
    "02-10": "National Umbrella Day",
    "02-11": "National Make a Friend Day",
    "02-12": "National Plum Pudding Day",
    "02-13": "National Galentine's Day",
    "02-14": "National Valentine's Day",
    "02-15": "National Gumdrop Day",
    "02-16": "National Almond Day",
    "02-17": "National Random Acts of Kindness Day",
    "02-18": "National Drink Wine Day",
    "02-19": "National Chocolate Mint Day",
    "02-20": "National Love Your Pet Day",
    "02-21": "National Sticky Bun Day",
    "02-22": "National Margarita Day",
    "02-23": "National Banana Bread Day",
    "02-24": "National Tortilla Chip Day",
    "02-25": "National Clam Chowder Day",
    "02-26": "National Pistachio Day",
    "02-27": "National Polar Bear Day",
    "02-28": "National Floral Design Day",
    "02-29": "National Leap Day",
    "03-01": "National Peanut Butter Lover's Day",
    "03-02": "National Read Across America Day",
    "03-03": "National Mulled Wine Day",
    "03-04": "National Pound Cake Day",
    "03-05": "National Cheese Doodle Day",
    "03-06": "National Oreo Cookie Day",
    "03-07": "National Cereal Day",
    "03-08": "National Peanut Cluster Day",
    "03-09": "National Crabmeat Day",
    "03-10": "National Blueberry Popover Day",
    "03-11": "National Oatmeal Nut Waffle Day",
    "03-12": "National Baked Scallops Day",
    "03-13": "National Coconut Torte Day",
    "03-14": "National Pi Day",
    "03-15": "National Pears Helene Day",
    "03-16": "National Artichoke Hearts Day",
    "03-17": "National St. Patrick's Day",
    "03-18": "National Lacy Oatmeal Cookie Day",
    "03-19": "National Chocolate Caramel Day",
    "03-20": "National Ravioli Day",
    "03-21": "National Crunchy Taco Day",
    "03-22": "National Goof Off Day",
    "03-23": "National Puppy Day",
    "03-24": "National Cheesesteak Day",
    "03-25": "National Waffle Day",
    "03-26": "National Spinach Day",
    "03-27": "National Spanish Paella Day",
    "03-28": "National Something on a Stick Day",
    "03-29": "National Lemon Chiffon Cake Day",
    "03-30": "National Pencil Day",
    "03-31": "National Tater Day",
    "04-01": "National April Fools Day",
    "04-02": "National Peanut Butter and Jelly Day",
    "04-03": "National Chocolate Mousse Day",
    "04-04": "National Cordon Bleu Day",
    "04-05": "National Deep Dish Pizza Day",
    "04-06": "National Caramel Popcorn Day",
    "04-07": "National Beer Day",
    "04-08": "National Empanada Day",
    "04-09": "National Unicorn Day",
    "04-10": "National Siblings Day",
    "04-11": "National Cheese Fondue Day",
    "04-12": "National Grilled Cheese Sandwich Day",
    "04-13": "National Peach Cobbler Day",
    "04-14": "National Dolphin Day",
    "04-15": "National Glazed Spiral Ham Day",
    "04-16": "National Eggs Benedict Day",
    "04-17": "National Cheeseball Day",
    "04-18": "National Animal Crackers Day",
    "04-19": "National Garlic Day",
    "04-20": "National Lookalike Day",
    "04-21": "National Chocolate Covered Cashews Day",
    "04-22": "National Earth Day",
    "04-23": "National Picnic Day",
    "04-24": "National Pigs in a Blanket Day",
    "04-25": "National Zucchini Bread Day",
    "04-26": "National Pretzel Day",
    "04-27": "National Prime Rib Day",
    "04-28": "National Blueberry Pie Day",
    "04-29": "National Shrimp Scampi Day",
    "04-30": "National Raisin Day",
    "05-01": "National May Day",
    "05-02": "National Truffle Day",
    "05-03": "National Raspberry Tart Day",
    "05-04": "National Star Wars Day",
    "05-05": "National Cinco de Mayo",
    "05-06": "National Beverage Day",
    "05-07": "National Roast Leg of Lamb Day",
    "05-08": "National Coconut Cream Pie Day",
    "05-09": "National Butterscotch Brownie Day",
    "05-10": "National Shrimp Day",
    "05-11": "National Eat What You Want Day",
    "05-12": "National Nutty Fudge Day",
    "05-13": "National Apple Pie Day",
    "05-14": "National Buttermilk Biscuit Day",
    "05-15": "National Chocolate Chip Day",
    "05-16": "National Cinnamon Roll Day",
    "05-17": "National Cherry Cobbler Day",
    "05-18": "National Cheese Souffle Day",
    "05-19": "National Devil's Food Cake Day",
    "05-20": "National Quiche Lorraine Day",
    "05-21": "National Strawberries and Cream Day",
    "05-22": "National Vanilla Pudding Day",
    "05-23": "National Taffy Day",
    "05-24": "National Escargot Day",
    "05-25": "National Wine Day",
    "05-26": "National Blueberry Cheesecake Day",
    "05-27": "National Grape Popsicle Day",
    "05-28": "National Brisket Day",
    "05-29": "National Coq au Vin Day",
    "05-30": "National Mint Julep Day",
    "05-31": "National Macaroon Day",
    "06-01": "National Hazelnut Cake Day",
    "06-02": "National Rocky Road Day",
    "06-03": "National Egg Day",
    "06-04": "National Cheese Day",
    "06-05": "National Gingerbread Day",
    "06-06": "National Applesauce Cake Day",
    "06-07": "National Chocolate Ice Cream Day",
    "06-08": "National Jelly-Filled Doughnut Day",
    "06-09": "National Strawberry Rhubarb Pie Day",
    "06-10": "National Iced Tea Day",
    "06-11": "National Corn on the Cob Day",
    "06-12": "National Peanut Butter Cookie Day",
    "06-13": "National Weed Your Garden Day",
    "06-14": "National Strawberry Shortcake Day",
    "06-15": "National Lobster Day",
    "06-16": "National Fudge Day",
    "06-17": "National Eat Your Vegetables Day",
    "06-18": "National Cherry Tart Day",
    "06-19": "National Martini Day",
    "06-20": "National Ice Cream Soda Day",
    "06-21": "National Peaches and Cream Day",
    "06-22": "National Onion Rings Day",
    "06-23": "National Pecan Sandy Day",
    "06-24": "National Pralines Day",
    "06-25": "National Strawberry Parfait Day",
    "06-26": "National Chocolate Pudding Day",
    "06-27": "National Orange Blossom Day",
    "06-28": "National Tapioca Day",
    "06-29": "National Almond Buttercrunch Day",
    "06-30": "National Mai Tai Day",
    "07-01": "National Gingersnap Day",
    "07-02": "National Anisette Day",
    "07-03": "National Chocolate Wafer Day",
    "07-04": "National Independence Day",
    "07-05": "National Graham Cracker Day",
    "07-06": "National Fried Chicken Day",
    "07-07": "National Strawberry Sundae Day",
    "07-08": "National Chocolate with Almonds Day",
    "07-09": "National Sugar Cookie Day",
    "07-10": "National Pina Colada Day",
    "07-11": "National Blueberry Muffin Day",
    "07-12": "National Pecan Pie Day",
    "07-13": "National French Fries Day",
    "07-14": "National Macaroni Day",
    "07-15": "National Gummy Worm Day",
    "07-16": "National Corn Fritters Day",
    "07-17": "National Peach Ice Cream Day",
    "07-18": "National Caviar Day",
    "07-19": "National Daiquiri Day",
    "07-20": "National Lollipop Day",
    "07-21": "National Junk Food Day",
    "07-22": "National Mango Day",
    "07-23": "National Vanilla Ice Cream Day",
    "07-24": "National Tequila Day",
    "07-25": "National Hot Fudge Sundae Day",
    "07-26": "National Bagelfest Day",
    "07-27": "National Scotch Day",
    "07-28": "National Milk Chocolate Day",
    "07-29": "National Lasagna Day",
    "07-30": "National Cheesecake Day",
    "07-31": "National Avocado Day",
    "08-01": "National Raspberry Cream Pie Day",
    "08-02": "National Ice Cream Sandwich Day",
    "08-03": "National Watermelon Day",
    "08-04": "National Chocolate Chip Cookie Day",
    "08-05": "National Oyster Day",
    "08-06": "National Root Beer Float Day",
    "08-07": "National Raspberries and Cream Day",
    "08-08": "National Zucchini Day",
    "08-09": "National Rice Pudding Day",
    "08-10": "National S'mores Day",
    "08-11": "National Raspberry Tart Day",
    "08-12": "National Julienne Fries Day",
    "08-13": "National Filet Mignon Day",
    "08-14": "National Creamsicle Day",
    "08-15": "National Lemon Meringue Pie Day",
    "08-16": "National Rum Day",
    "08-17": "National Vanilla Custard Day",
    "08-18": "National Soft Ice Cream Day",
    "08-19": "National Potato Day",
    "08-20": "National Lemonade Day",
    "08-21": "National Spumoni Day",
    "08-22": "National Pecan Torte Day",
    "08-23": "National Sponge Cake Day",
    "08-24": "National Peach Pie Day",
    "08-25": "National Banana Split Day",
    "08-26": "National Cherry Popsicle Day",
    "08-27": "National Pots de Creme Day",
    "08-28": "National Cherry Turnover Day",
    "08-29": "National Chop Suey Day",
    "08-30": "National Toasted Marshmallow Day",
    "08-31": "National Trail Mix Day",
    "09-01": "National No Rhyme or Reason Day",
    "09-02": "National Blueberry Popsicle Day",
    "09-03": "National Welsh Rarebit Day",
    "09-04": "National Macadamia Nut Day",
    "09-05": "National Cheese Pizza Day",
    "09-06": "National Coffee Ice Cream Day",
    "09-07": "National Acorn Squash Day",
    "09-08": "National Date Nut Bread Day",
    "09-09": "National Wiener Schnitzel Day",
    "09-10": "National TV Dinner Day",
    "09-11": "National Hot Cross Bun Day",
    "09-12": "National Chocolate Milkshake Day",
    "09-13": "National Peanut Day",
    "09-14": "National Cream Filled Donut Day",
    "09-15": "National Linguine Day",
    "09-16": "National Guacamole Day",
    "09-17": "National Apple Dumpling Day",
    "09-18": "National Cheeseburger Day",
    "09-19": "National Butterscotch Pudding Day",
    "09-20": "National Pepperoni Pizza Day",
    "09-21": "National Pecan Cookie Day",
    "09-22": "National Ice Cream Cone Day",
    "09-23": "National White Chocolate Day",
    "09-24": "National Cherries Jubilee Day",
    "09-25": "National Cooking Day",
    "09-26": "National Pancake Day",
    "09-27": "National Corned Beef Hash Day",
    "09-28": "National Strawberry Cream Pie Day",
    "09-29": "National Coffee Day",
    "09-30": "National Mulberry Day",
    "10-01": "National Homemade Cookies Day",
    "10-02": "National Fried Scallops Day",
    "10-03": "National Caramel Custard Day",
    "10-04": "National Taco Day",
    "10-05": "National Apple Betty Day",
    "10-06": "National Noodle Day",
    "10-07": "National Frappe Day",
    "10-08": "National Fluffernutter Day",
    "10-09": "National Moldy Cheese Day",
    "10-10": "National Cake Decorating Day",
    "10-11": "National Sausage Pizza Day",
    "10-12": "National Gumbo Day",
    "10-13": "National Pumpkin Day",
    "10-14": "National Dessert Day",
    "10-15": "National Mushroom Day",
    "10-16": "National Liqueur Day",
    "10-17": "National Pasta Day",
    "10-18": "National Chocolate Cupcake Day",
    "10-19": "National Seafood Bisque Day",
    "10-20": "National Brandied Fruit Day",
    "10-21": "National Pumpkin Cheesecake Day",
    "10-22": "National Nut Day",
    "10-23": "National Boston Cream Pie Day",
    "10-24": "National Bologna Day",
    "10-25": "National Greasy Food Day",
    "10-26": "National Pumpkin Day",
    "10-27": "National American Beer Day",
    "10-28": "National Chocolate Day",
    "10-29": "National Oatmeal Day",
    "10-30": "National Candy Corn Day",
    "10-31": "National Halloween",
    "11-01": "National Vinegar Day",
    "11-02": "National Deviled Egg Day",
    "11-03": "National Sandwich Day",
    "11-04": "National Candy Day",
    "11-05": "National Doughnut Day",
    "11-06": "National Nachos Day",
    "11-07": "National Bittersweet Chocolate with Almonds Day",
    "11-08": "National Harvey Wallbanger Day",
    "11-09": "National Scrapple Day",
    "11-10": "National Vanilla Cupcake Day",
    "11-11": "National Veterans Day",
    "11-12": "National French Dip Day",
    "11-13": "National Indian Pudding Day",
    "11-14": "National Pickle Day",
    "11-15": "National Raisin Bran Cereal Day",
    "11-16": "National Fast Food Day",
    "11-17": "National Baklava Day",
    "11-18": "National Vichyssoise Day",
    "11-19": "National Carbonated Beverage with Caffeine Day",
    "11-20": "National Peanut Butter Fudge Day",
    "11-21": "National Stuffing Day",
    "11-22": "National Cranberry Relish Day",
    "11-23": "National Cashew Day",
    "11-24": "National Espresso Day",
    "11-25": "National Parfait Day",
    "11-26": "National Cake Day",
    "11-27": "National Bavarian Cream Pie Day",
    "11-28": "National French Onion Soup Day",
    "11-29": "National Lemon Cream Pie Day",
    "11-30": "National Mousse Day",
    "12-01": "National Pie Day",
    "12-02": "National Fritters Day",
    "12-03": "National Apple Day",
    "12-04": "National Cookie Day",
    "12-05": "National Comfort Food Day",
    "12-06": "National Gazpacho Day",
    "12-07": "National Cotton Candy Day",
    "12-08": "National Brownie Day",
    "12-09": "National Pastry Day",
    "12-10": "National Lager Day",
    "12-11": "National Noodle Ring Day",
    "12-12": "National Cocoa Day",
    "12-13": "National Popcorn String Day",
    "12-14": "National Bouillabaisse Day",
    "12-15": "National Cupcake Day",
    "12-16": "National Chocolate Covered Anything Day",
    "12-17": "National Maple Syrup Day",
    "12-18": "National Roast Suckling Pig Day",
    "12-19": "National Hard Candy Day",
    "12-20": "National Sangria Day",
    "12-21": "National Coquito Day",
    "12-22": "National Date Nut Bread Day",
    "12-23": "National Pfeffernusse Day",
    "12-24": "National Eggnog Day",
    "12-25": "National Christmas Day",
    "12-26": "National Candy Cane Day",
    "12-27": "National Fruitcake Day",
    "12-28": "National Chocolate Day",
    "12-29": "National Pepper Pot Day",
    "12-30": "National Bicarbonate of Soda Day",
    "12-31": "National Champagne Day"
]

func todayNationalDay() -> String? {
    let formatter = DateFormatter()
    formatter.dateFormat = "MM-dd"
    let key = formatter.string(from: Date())
    return nationalDays[key]
}
